version: '3'
services:
  roamingkitchen:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_GOOGLE_MAPS_API_KEY: ${React api key}
    labels:
      - "bunnyshell-hackathon"
    deploy:
      replicas: 1
    ports:
      - 3000:3000
    environment:
      - "REACT_APP_GOOGLE_MAPS_API_KEY={google maps api key}"
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    labels:
      - "bunnyshell-hackathon"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
      replicas: 3
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST={postgreshost}
      - POSTGRES_DB={postgresdb}
      - POSTGRES_PORT=5432
      - POSTGRES_USER={postgresuser}
      - POSTGRES_PASSWORD={postgrespassword}
      - aiaccesskey={openaikey}
      - imageaccesskey={openaikey}
      - awsaccesskey={awsaccesskey}
      - awssecretkey={awssecretkey}
      - squareaccesstoken={squareaccesstoken}