version: '3'
services:
  roamingkitchen:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
      replicas: 2
    ports:
      - 3000:3000
    environment:
      - "REACT_APP_GOOGLE_MAPS_API_KEY={google maps api key}"
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
      replicas: 2
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=theroamingkitchen
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - aiaccesskey={openaikey}
      - imageaccesskey={openaikey}
      - awsaccesskey={awsaccesskey}
      - awssecretkey={awssecretkey}
      - squareaccesstoken={squareaccesstoken}
    depends_on:
      - db
  db:
    image: postgres
    container_name: theroamingkitchen
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: theroamingkitchen
    ports:
      - "5432:5432"
